// Generated by gencpp from file speaker/record.msg
// DO NOT EDIT!


#ifndef SPEAKER_MESSAGE_RECORD_H
#define SPEAKER_MESSAGE_RECORD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speaker
{
template <class ContainerAllocator>
struct record_
{
  typedef record_<ContainerAllocator> Type;

  record_()
    : record()  {
    }
  record_(const ContainerAllocator& _alloc)
    : record(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _record_type;
  _record_type record;




  typedef boost::shared_ptr< ::speaker::record_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speaker::record_<ContainerAllocator> const> ConstPtr;

}; // struct record_

typedef ::speaker::record_<std::allocator<void> > record;

typedef boost::shared_ptr< ::speaker::record > recordPtr;
typedef boost::shared_ptr< ::speaker::record const> recordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speaker::record_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speaker::record_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speaker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'speaker': ['/home/dan/Desktop/speaker_detection/speaker_recoginition/ros_ws/src/speaker/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speaker::record_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speaker::record_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speaker::record_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speaker::record_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speaker::record_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speaker::record_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speaker::record_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ab1fcac04e7ea8eb98e9e4e4e856d45";
  }

  static const char* value(const ::speaker::record_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ab1fcac04e7ea8eULL;
  static const uint64_t static_value2 = 0xb98e9e4e4e856d45ULL;
};

template<class ContainerAllocator>
struct DataType< ::speaker::record_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speaker/record";
  }

  static const char* value(const ::speaker::record_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speaker::record_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] record\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::speaker::record_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speaker::record_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.record);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct record_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speaker::record_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speaker::record_<ContainerAllocator>& v)
  {
    s << indent << "record[]" << std::endl;
    for (size_t i = 0; i < v.record.size(); ++i)
    {
      s << indent << "  record[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.record[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEAKER_MESSAGE_RECORD_H
